{{- if .Values.openwebui.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
type: Opaque
stringData:
  openai-api-key: {{ .Values.openwebui.openaiApiKey | quote }}
{{- end }}
