apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.opencloud.adminPassword | quote }}
