{{- if and .Values.httpRoute.enabled .Values.httpRoute.allowGatewayTraffic }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "excalidraw.fullname" . }}-gateway
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "excalidraw.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
        - ports:
            - port: {{ .Values.httpRoute.gatewayTrafficPort | default .Values.service.targetPort | quote }}
              protocol: TCP
{{- end }}
